<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>Mapped_Employee_Select</name>
   <tag></tag>
   <elementGuidId>afb3eaac-3287-4bdd-888b-fb26e1808d40</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.TextView</value>
      <webElementGuid>86d141e7-05d0-49ce-aafa-8d881e584f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8ce6a95a-e947-4b51-b345-b7f70194725d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SUDHAN_E1_VAN LastNAme1909951901</value>
      <webElementGuid>e452e62c-33a5-4a09-9557-24675e68cc02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resource-id</name>
      <type>Main</type>
      <value>com.ivy.bimbomx.mexico.view.uat:id/tv_employeename</value>
      <webElementGuid>671c3e94-7ca3-4907-8868-8c21f80b152b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>com.ivy.bimbomx.mexico.view.uat</value>
      <webElementGuid>3502ee0b-1d1e-4b9c-bff9-3ec051e57f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checkable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>95e30ff1-e7fc-4a46-8de2-dbcb20027f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ceff56d4-495f-4188-a739-c752a93e2d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clickable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d142bba1-2ad0-44e8-92ec-c75d665401ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dd6d6886-3836-47ae-bafd-af712ed4b166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>639e4880-a163-4501-8609-a9ec522d3cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2bf47171-4e2f-482b-8e23-789fad8fd693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrollable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2737f18a-0b58-4a5a-ba2c-f5d6b9f652bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>long-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b56eefb5-afa4-4526-b8e3-17254647946c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>password</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5482b55b-ea99-4e95-bb66-d0995de150a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>68617e46-cbfd-4077-8455-42b62ea36b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2524b6b6-2665-4c81-a457-93ced1d99ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>363</value>
      <webElementGuid>dc3710cb-4f94-478d-936c-00486f45903f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1080</value>
      <webElementGuid>0e63b2e7-fe88-40c8-af9f-13544b902dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>136</value>
      <webElementGuid>2cbf40af-1f81-485f-bfa1-c88ac97ce52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>a11y-focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>258aee2a-522c-4d73-8d16-2183a721de52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>a11y-important</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bbbb907f-349e-4d14-9a36-d74519a6ae17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bounds</name>
      <type>Main</type>
      <value>[0,363][1080,499]</value>
      <webElementGuid>d9d62ef8-c18e-48f9-9a70-ec3d30979cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f13a1d3b-675f-488e-ac1e-84db58510bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>context-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5da22697-6dd7-4530-9e34-42056b18a16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dismissable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d047bdc-88fc-4e7a-9d90-6377edaef746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7207e123-a7b6-410a-b6bd-fae03e51714c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>drawing-order</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>031eb380-3b1f-46a1-b38e-1e760be008da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>heading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6c2b5463-78d0-4be0-b712-7000cff164d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>live-region</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ff7ee8b6-23b6-4f0a-b590-1d401fb7b8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>screen-reader-focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>76e546b4-caaf-49a8-b3ef-6424cbd3eb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>showing-hint</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5384c67b-41ec-42ed-ad3d-b2cf7bbfc279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-entry-key</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1ae426a5-0536-450e-969d-a1b76281ffa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.RelativeLayout[1]/android.widget.TextView[1]</value>
      <webElementGuid>eb8683ac-a52a-421c-8b24-a72c6792d500</webElementGuid>
   </webElementProperties>
   <locator>com.ivy.bimbomx.mexico.view.uat:id/tv_employeename</locator>
   <locatorCollection>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**[`enabled == 1`]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//hierarchy/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/androidx.recyclerview.widget.RecyclerView[1]/android.widget.RelativeLayout[1]/android.widget.TextView[1]</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>NAME</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>enabled == 1</value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>android.widget.TextView</value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@class = 'android.widget.TextView' and (@text = 'SUDHAN_E1_VAN LastNAme1909951901' or . = 'SUDHAN_E1_VAN LastNAme1909951901') and @resource-id = 'com.ivy.bimbomx.mexico.view.uat:id/tv_employeename']</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value></value>
      </entry>
      <entry>
         <key>ID</key>
         <value>com.ivy.bimbomx.mexico.view.uat:id/tv_employeename</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value>new UiSelector().className(&quot;android.widget.TextView&quot;).text(&quot;SUDHAN_E1_VAN LastNAme1909951901&quot;).resourceId(&quot;com.ivy.bimbomx.mexico.view.uat:id/tv_employeename&quot;).packageName(&quot;com.ivy.bimbomx.mexico.view.uat&quot;).enabled(true).clickable(true).longClickable(false).checkable(false).checked(false).focusable(true).focused(false).scrollable(false).selected(false).index(0)</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ID</locatorStrategy>
   <platform>ANDROID</platform>
</MobileElementEntity>
